name: Spack Monitor Analysis
on:
  pull_request: []
  push:
    branches:
      - main

jobs:
  changes:
    name: "Changed Files"
    runs-on: ubuntu-latest
    outputs:
      changed_file: ${{ steps.files.outputs.added_modified }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
        with:
          format: 'json'

  build:
    needs:
      - changes
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
                    # These containers have one tag (latest) across architectures
        container: ['ghcr.io/buildsi/spack-ubuntu-18.04',
                    'ghcr.io/buildsi/spack-ubuntu-20.04',
                    'ghcr.io/buildsi/spack-centos-7',
                    'ghcr.io/buildsi/spack-centos-8',
                    'ghcr.io/buildsi/spack-fedora',
                    
                    # These have tags corresponding to gcc version and only amd64
                    'ghcr.io/buildsi/ubuntu:gcc-8.1.0',
                    'ghcr.io/buildsi/ubuntu:gcc-7.3.0',
                    'ghcr.io/buildsi/ubuntu:gcc-9.4.0',
                    'ghcr.io/buildsi/ubuntu:gcc-11.2.0',
                    'ghcr.io/buildsi/ubuntu:gcc-4.9.4',
                    'ghcr.io/buildsi/ubuntu:gcc-10.3.0']

        arch: ['linux/amd64'] # ,'linux/ppc64le','linux/arm64']
        changed_file: ${{ fromJson(needs.changes.outputs.changed_file) }}

    container:
      image: ${{ matrix.container }}
      options: "--platform=${{ matrix.arch }}"

    name: ${{ matrix.changed_file }} ${{ matrix.container }} ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Space For Build
        run: |        
          ls /usr/share
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc

      - name: Run Build
        run: |
           printf "Preparing to run ${{ matrix.changed_file }}\n"
           /bin/bash ./entrypoint.sh ${{ matrix.changed_file }}
