name: Spack Monitor Analysis
on:
  pull_request: []
  push:
    branches:
      - main

jobs:
  changes:
    name: "Changed Files"
    runs-on: ubuntu-latest
    outputs:
      changed_file: ${{ steps.files.outputs.added_modified }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
        with:
          format: 'json'

  build:
    needs:
      - changes
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        container: ['ghcr.io/buildsi/spack-ubuntu-18.04',
                    'ghcr.io/buildsi/spack-ubuntu-20.04',
                    'ghcr.io/buildsi/spack-centos-7',
                    'ghcr.io/buildsi/spack-centos-8',
                    'ghcr.io/buildsi/spack-fedora']
        arch: ['linux/amd64'] # ,'linux/ppc64le','linux/arm64']
        changed_file: ${{ fromJson(needs.changes.outputs.changed_file) }}

    container:
      image: ${{ matrix.container }}
      options: "--platform=${{ matrix.arch }}"

    name: ${{ matrix.changed_file }} ${{ matrix.container }} ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check that file exists
        run: |
          filename="${{ matrix.changed_file }}"
          printf "Found changed file ${filename}\n"

          dobuild=false
          if [[ $filename == specs* ]]; then
              printf "Found specs file!\b"
              relname=$(basename $filename)
              libname=$(echo "${relname%.*}")
              dobuild=true
          fi 
          echo "keepgoing=${dobuild}" >> $GITHUB_ENV

      - name: Make Space For Build
        if: ${{ env.keepgoing == 'true' }}
        run: |
          ls /usr/share
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc

      - name: Run Build
        if: ${{ env.keepgoing == 'true' }}
        run: ./entrypoint.sh ${{ env.libname }}
#      - name: Set up QEMU
#        if: ${{ env.keepgoing == 'true' }}
#        uses: docker/setup-qemu-action@v1

#      - name: Set up Docker Buildx
#        if: ${{ env.keepgoing == 'true' }}
#        uses: docker/setup-buildx-action@v1

#      - name: Build and export to Docker
#        if: ${{ env.keepgoing == 'true' }}
#        uses: docker/build-push-action@v2
#        with:
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          platforms: ${{ matrix.arch }}
#          load: true
#          tags: ${{ env.libname }}
#          build-args: |
#            base=${{ matrix.container }}

#      - name: Install and Analyze
#        if: ${{ env.keepgoing == 'true' }}
#        run: |
#          docker run --it --platform=${{ matrix.arch }} --rm ${{ env.libname }} ${{ env.filename }}
