name: GCC Build Matrices

on: workflow_dispatch

jobs:
  generate:
    name: Generate Build Matrix
    runs-on: ubuntu-latest
    outputs:
      dockerbuild_matrix: ${{ steps.dockerbuild.outputs.dockerbuild_matrix }}
      empty_matrix: ${{ steps.dockerbuild.outputs.dockerbuild_matrix_empty }}

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0

    - name: Generate Build Matrix
      uses: vsoch/uptodate@main
      id: dockerbuild
      with: 
        root: docker
        parser: dockerbuild
        flags: "--all"

    - name: View and Check Build Matrix Result
      env:
        result: ${{ steps.dockerbuild.outputs.dockerbuild_matrix }}
      run: |
        echo ${result}
        if [[ "${result}" == "[]" ]]; then
          printf "The matrix is empty, will not trigger next workflow.\n"
        else
          printf "The matrix is not empty, and we should continue on to the next workflow.\n"
        fi

  build:
    needs:
      - generate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        result: ${{ fromJson(needs.generate.outputs.dockerbuild_matrix) }}

                               # https://repo.anaconda.com/archive/
        arch: [['linux/amd64', 'Anaconda3-2021.05-Linux-x86_64.sh'],
               ['linux/ppc64le', 'Anaconda3-2021.05-Linux-ppc64le.sh']]
               # ['linux/arm64', 'Anaconda3-2021.05-Linux-aarch64.sh']]
               # There is a bug with docker and arm, skipping for now

    if: ${{ needs.generate.outputs.empty_matrix == 'false' }}

    name: "Build ${{ matrix.result.container_name }} ${{ matrix.arch[0] }}" 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Make Space For Build
      run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc

    - name: Pull Docker Layers
      env:
        container: ${{ matrix.result.container_name }}
      run: docker pull ghcr.io/buildsi/${container} || exit 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Prepare ${{ matrix.result.container_name }}
      id: builder
      env:
        container: ${{ matrix.result.container_name }}
        prefix: ${{ matrix.result.command_prefix }}
        filename: ${{ matrix.result.filename }}
      run: |
        basedir=$(dirname $filename)
        printf "Base directory is ${basedir}\n"
        # Get relative path to PWD and generate dashed name from it
        cd $basedir
        echo "${prefix} -t ${container} ."
        build_args="$(echo "${prefix#*--build-arg}")"
        # Add build-arg for anaconda download
        echo "dockerfile_dir=${basedir}" >> $GITHUB_ENV
        echo "build_args=${build_args}" >> $GITHUB_ENV
        echo "container=${container}" >> $GITHUB_ENV
        echo "filename=${filename}" >> $GITHUB_ENV

    - name: Build ${{ matrix.dockerfile[1] }}
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.dockerfile_dir }}
        file: ${{ env.filename }}
        platforms: ${{ matrix.arch[0] }}
        load: true
        build-args: |
          ${{ env.build_args }}
          anaconda_url=${{ matrix.arch[1] }}
        tags: ghcr.io/buildsi/${{ env.container }}

    - name: Derive Compiler Labels
      id: labels
      run: |
        docker run -i --rm ghcr.io/buildsi/${{ env.container }} spack compiler list --flat > compilers.txt
        labels=$(echo $(tr '\r\n' ',' < compilers.txt))
        labels="org.spack.compilers=${labels}"
        printf "Saving compiler labels ${labels}\n"         
        echo "compiler_labels=${labels}" >> $GITHUB_ENV
      
    - name: Deploy ${{ matrix.dockerfile[1] }}
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.dockerfile_dir }}
        file: ${{ env.filename }}
        platforms: ${{ matrix.arch[0] }}
        push: ${{ github.event_name != 'pull_request' }}
        build-args: |
            ${{ env.build_args }}
            anaconda_url=${{ matrix.arch[1] }}
        tags: ghcr.io/buildsi/${{ env.container }}
        labels: ${{ env.compiler_labels }}
